language: R
sudo: required

r_packages:
  - covr

apt_packages:
  - r-cran-rjags

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
  email:
    recipients:
      - audrey.beliveau@uwaterloo.ca
    on_success: change
    on_failure: always
